import { Routes } from '@angular/router';
import { HomeComponent } from './pages/home/home';
import { BookListComponent } from './pages/book-list/book-list';
import { BookDetailsComponent } from './pages/book-details/book-details';
import { CartComponent } from './pages/cart/cart';
import { CheckoutComponent } from './pages/checkout/checkout';
import { OrderHistoryComponent } from './pages/order-history/order-history';
import { UserProfileComponent } from './pages/user-profile/user-profile';
import { LoginComponent } from './pages/login/login';
import { RegisterComponent } from './pages/register/register';
import { AdminLoginComponent } from './pages/admin/admin-login/admin-login';
import { DashboardComponent } from './pages/admin/dashboard/dashboard';
import { ManageBooksComponent } from './pages/admin/manage-books/manage-books';
import { AddBookComponent } from './pages/admin/add-book/add-book';
import { ManageOrdersComponent } from './pages/admin/manage-orders/manage-orders';
import { ManageUsersComponent } from './pages/admin/manage-users/manage-users';

export const routes: Routes = [
  { path: '', component: HomeComponent },
  { path: 'books', component: BookListComponent },
  { path: 'book/:id', component: BookDetailsComponent },
  { path: 'cart', component: CartComponent },
  { path: 'checkout', component: CheckoutComponent },
  { path: 'orders', component: OrderHistoryComponent },
  { path: 'profile', component: UserProfileComponent },
  { path: 'login', component: LoginComponent },
  { path: 'register', component: RegisterComponent },
  { path: 'admin/login', component: AdminLoginComponent },
  { path: 'admin/dashboard', component: DashboardComponent },
  { path: 'admin/books', component: ManageBooksComponent },
  { path: 'admin/add-book', component: AddBookComponent },
  { path: 'admin/edit-book/:id', component: AddBookComponent },
  { path: 'admin/orders', component: ManageOrdersComponent },
  { path: 'admin/users', component: ManageUsersComponent },
  { path: '**', redirectTo: '' }
];
